name: Deploy Node.js to Azure Web App - Runlog

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Zip artifact
        run: zip -r release.zip . -x ".git/*"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E29245AA4AAB4298B83B47F6A7D9C697 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_71F197CC196840CCBDFDC29F40B4D1D8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_921A232ED5CF49EDBAF402409EFEEBA8 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Runlog'
          slot-name: 'Production'
          package: release.zip